services:
  bookdatabase:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data/instance:/app/instance
      - ./data/uploads:/app/static/uploads
    environment:
      - SECRET_KEY=${SECRET_KEY:-}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY:-}
      - PUSHOVER_APP_TOKEN=${PUSHOVER_APP_TOKEN:-}
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN:-}
      - GOOGLEBOOKS_TOKEN=${GOOGLEBOOKS_TOKEN:-}
    restart: unless-stopped
